# Generated by Django 5.1.2 on 2024-10-31 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='election',
            name='allowed_prefix',
            field=models.CharField(blank=True, help_text="Comma-separated list of matric prefixes allowed to vote (e.g., 'CSC, EEE, MTH').", max_length=100, null=True),
        ),
    ]
