# Generated by Django 5.1.2 on 2024-10-31 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0002_election_allowed_prefix'),
    ]

    operations = [
        migrations.AddField(
            model_name='election',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
